apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-school-deployment
spec:
  selector:
    matchLabels:
      app: ms-school
  replicas: 3
  template:
    metadata:
      labels:
        app: ms-school
    spec:
      containers:
        - name: ms-school
          image: ms-school:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080